name: Build Iris

on:
   push

jobs:
   build-iris:
      runs-on: ubuntu-latest

      env:
         CI: TRUE

      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Install nox
           run: pip install nox 

         - name: Run nox
           run: |
              cd projects/iris
              nox -f notebooks/noxfile.py	
